<a href="https://colab.research.google.com/github/delos001/DS_Recipes/blob/master/BasicPythonTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
arr = [5, 19, 5, 99, 30, 3, 20, 21]


if len(arr) <= 1:
  print(arr)

In [28]:
pivot = arr[len(arr) // 2]
print(pivot)

30


In [29]:
left = [x for x in arr if x < pivot]

print(left)

[5, 19, 5, 3, 20, 21]


In [33]:
middle = [x for x in arr if x == pivot]

print(middle)

[30]


In [31]:
right = [x for x in arr if x > pivot]

print(right)

[99]


In [3]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

#print(quicksort([3,6,8,10,1,2,19,20,1,5,50,99]))

print(quicksort(arr))

[3, 5, 5, 19, 20, 21, 30, 99]


In [4]:
hello = 'hello'
world = 'world'

print(hello, len(hello))

hello 5


In [6]:
print(hello + ' ' + world)

hello world


In [8]:
hw12 = '{} {} {}' .format(hello, world, 12)
print(hw12)

hello world 12


In [14]:
s = 'hello'

print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ello)'))


Hello
HELLO
  hello
 hello 
he(ello)(ello)o


In [16]:
z = [1, 2, 9]

print(z, z[2])
print(z[-1])

[1, 2, 9] 9
9


In [18]:
z[2] = 'foo'
print(z)

[1, 2, 'foo']


In [0]:
z = z + z

In [20]:
print(z)

[1, 2, 'foo', 1, 2, 'foo']


In [0]:
z = z[0:3]

In [25]:
print(z)

[1, 2, 'foo']


In [23]:
z.append('foo')
print(z)

[1, 2, 'foo']


In [26]:
z.append('bar')
print(z)

[1, 2, 'foo', 'bar']


In [27]:
z.pop()

'bar'

In [28]:
print(z)

[1, 2, 'foo']


In [30]:
ran = list(range(10))
print(ran)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [32]:
print(ran[2])
print(ran[0:5])
print(ran[2:8])
print(ran[7:])
print(ran[:])
print(ran[:-1])
print(ran[-1])

2
[0, 1, 2, 3, 4]
[2, 3, 4, 5, 6, 7]
[7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]
9


In [33]:
animals = ['cat', 'dog', 'bird', 'cow']

for animal in animals:
  print(animal)

cat
dog
bird
cow


In [34]:
for idx, animal in enumerate(animals):
  print('{}: {}'. format(idx + 1, animal))


1: cat
2: dog
3: bird
4: cow


In [36]:
nums = [1, 2, 3, 4]

sqd = []
for num in nums:
  sqd.append(num**2)

  print(sqd)


[1]
[1, 4]
[1, 4, 9]
[1, 4, 9, 16]


In [37]:
print(sqd)

[1, 4, 9, 16]


In [38]:
nums = [1,2,3,4]

sqd = [num**2 for num in nums]

print(sqd)

[1, 4, 9, 16]


In [41]:
nums = [1,2,3,4]

evnsqd = [num**2 for num in nums if num % 2 == 0]
print(evnsqd)

[4, 16]


In [42]:
68*40*52

141440

In [0]:
animals = {'cat': 'cute', 'dog': 'furry'}

In [2]:
animals['cat']

'cute'

In [3]:
print('cat' in animals)

True


In [0]:
animals['fish'] = 'wet'

In [5]:
animals

{'cat': 'cute', 'dog': 'furry', 'fish': 'wet'}

In [7]:
del animals['fish']

print(animals)

{'cat': 'cute', 'dog': 'furry'}


In [0]:
d = {'dog': 4, 'human': 2, 'spider': 8}

In [19]:
for animal, leg in d.items():
  print('A {} has {} legs'.format(animal, leg))

A dog has 4 legs
A human has 2 legs
A spider has 8 legs


In [0]:
legs = {}

In [21]:
sqd = [0, 1, 2, 3, 4]

result = {x: x**2 for x in sqd if x % 2 == 0}
print(result)

{0: 0, 2: 4, 4: 16}


In [0]:
animals = {'cat', 'dog'}

In [24]:
animals.add('fish')
print(animals)
print(len(animals))

{'dog', 'cat', 'fish'}
3


In [26]:
animals.remove('fish')
print(len(animals))

2


In [28]:
animals = {'cat', 'dog', 'fish'}

for idx, animal in enumerate(animals):
  print('ind: {} {}'.format(idx + 1, animal))

ind: 1 dog
ind: 2 cat
ind: 3 fish


In [35]:
from math import sqrt

print({int(sqrt(x)) for x in range(30)})

{0, 1, 2, 3, 4, 5}


In [34]:
sqrt(29)

5.385164807134504

In [0]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)       # Create a tuple
print(type(t))
print(d[t])       
print(d[(1, 2)])

In [36]:
d = {(x, x + 1): x for x in range(10)}
print(d)

{(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4, (5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}


In [37]:
t = (5, 6)
print(type(t))

<class 'tuple'>


In [38]:
print(d[t])

5


In [42]:
print(d[(1, 2)])

1


In [0]:
def sign(x):
  if x > 0:
    return 'positive'
  elif x < 0:
    return 'negative'
  else:
    return 'zero'

In [50]:
for x in [-1, 0, 1]:
  print(sign(x))

negative
zero
positive


In [0]:
def hello(name, loud = False):
  if loud:
    print('HELLO {}'.format(name.upper()))

  else:
    print('Hello {}'.format(name))



In [57]:
hello('Pam', loud = True)
hello('Pam')

HELLO PAM
Hello Pam


In [0]:
import numpy as np

In [59]:
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [66]:
print(type(a), a.shape, a[0], a[1], a[2], a[3])

<class 'numpy.ndarray'> (5,) 1 2 3 4


In [64]:
a[4] = 0

print(a)

[1 2 3 4 0]


In [68]:
b = np.array([[1, 2, 3],
             [4, 5, 6]])

print(b, b.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [70]:
print(b[0,1], b[1,1], b[1,0])

2 5 4


In [73]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [74]:
b = np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [75]:
z = 7

c = np.full((3,3), z)
print(c)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [77]:
d = np.eye(3)
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [79]:
e = np.random.random(size = (5,5))
print(e)

[[0.27547133 0.34975736 0.27635786 0.858638   0.74097399]
 [0.52511599 0.6477946  0.24327164 0.15048306 0.214206  ]
 [0.46626613 0.95230188 0.00515608 0.92505556 0.40310006]
 [0.3952282  0.55458886 0.40797626 0.48155134 0.28395892]
 [0.00718015 0.54689443 0.81799151 0.26783945 0.68512135]]


In [81]:
a = np.array([[1,2,3,4], [5,6,7,8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [85]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]
