###  Python Basics Tutorial

####   Numpy Basics Tutorial

####  Machine Learning Mastery with Python
####  Jason Brownlee

#### Numpy reference: http://docs.scipy.org/doc/numpy/reference/

In [1]:
import scipy
import numpy
import matplotlib
import pandas
import sklearn

In [4]:
print('scipy: %s' % scipy.__version__)
print('numpy: %s' % numpy.__version__)
print('matplotlib: %s' % matplotlib.__version__)
print('pandas: %s' % pandas.__version__)
print('sklearn: %s' % sklearn.__version__)

scipy: 1.3.1
numpy: 1.16.5
matplotlib: 3.1.1
pandas: 0.25.1
sklearn: 0.21.3


##  NumPy Crash Course


#### Create an Array

In [5]:
mylist = [1, 2, 3]
myarray = numpy.array(mylist)

print(myarray)
print(myarray.shape)

[1 2 3]
(3,)


#### Access Data

In [20]:
mylist = [[1, 2, 3], [3, 4, 5]]
myarray = numpy.array(mylist)

print(myarray)

# prints numb of rows then numb of cols
print(myarray.shape)

print('First row: %s' % myarray[0])
print('Last row: %s' % myarray[-1])
print('Specific row and column: %s' % myarray[1,2])
print('Entire column: %s' % myarray[: ,2])

[[1 2 3]
 [3 4 5]]
(2, 3)
First row: [1 2 3]
Last row: [3 4 5]
Specific row and column: 5
Entire column: [3 5]


#### Arithmetic

In [23]:
myarray1 = numpy.array([2, 2, 2])
myarray2 = numpy.array([3, 3, 3])

print('Addition of 1 and 2: %s' % (myarray1 + myarray2))
print('Multplication of 1 and 2: %s' % (myarray1 * myarray2))

Addition of 1 and 2: [5 5 5]
Multplication of 1 and 2: [6 6 6]


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4]])

print(np.sum(x))
print(np.sum(x, axis = 0)) # compute sum of columns
print(np.sum(x, axis = 1)) # compute sum of rows